version : '3.0'

services:
  db:
    container_name: gql-db
    image: postgres
    ports :
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gql
      POSTGRES_PASSWORD: gqlpassword

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
    networks:
      - mynetwork

networks:
  mynetwork:
  
volumes:
  postgres_data: